### ISSUE TITLE
Windows IPC close method doing nothing

### ISSUE THREAD

**Issue by Bowarc** [vionya/discord-rich-presence#37]
I maybe am missing something but it looks like the `.close` method in `DiscordIpc`'s implementation on windows do nothing

Windows's implementation: 
```rust
fn close(&mut self) -> Result<()> {
    let data = json!({});
    if self.send(data, 2).is_ok() {} // ?

    let socket = self.socket.as_mut().ok_or(Error::NotConnected)?;
    socket.flush()?;

    Ok(())
}
```

Unix's implementation
```rust
fn close(&mut self) -> Result<()> {
    let data = json!({});
    if self.send(data, 2).is_ok() {} // ?

    let socket = self.socket.as_mut().ok_or(Error::NotConnected)?;

    socket.flush()?;
    match socket.shutdown(Shutdown::Both) {
        Ok(()) => (),
        Err(_err) => (),
    };

    Ok(())
}
```

Has something been forgotten ?

**Comment by vionya** [comment]
so on windows the pipes are just normal file handles, and the `File` API doesnt have an explicit way to close a file (other than dropping it). i guess i figured that i didnt need to do anything to accomplish this when i first implemented windows (oops). i can add a call to `std::mem::drop` in the windows code, which should be explicit enough?

**Comment by Bowarc** [comment]
> i can add a call to std::mem::drop in the windows code, which should be explicit enough?

If the code is doing what's expected, no need to modify it, maybe a comment would clarify this for any future reader ?

**Comment by vionya** [comment]
yea I think you're right, I didn't properly drop the file when I first wrote this lol. I'll update the code to properly drop the file

**Comment by vionya** [comment]
hi, I just pushed a change that *should* resolve this (sorry for taking so long 😭). if you're able, can you try using the latest git version to confirm if it solves the issue for you?

**Comment by UnknownSuperficialNight** [comment]
> hi, I just pushed a change that _should_ resolve this (sorry for taking so long 😭). if you're able, can you try using the latest git version to confirm if it solves the issue for you?

Tested on Windows not resolved for me still same effect as before

Using:
```Rust
discord-rich-presence = { git = "https://github.com/vionya/discord-rich-presence.git", branch = "main" }
```

For reference here is the function I'm calling to close the connection in my program.

```Rust
pub fn stop_rpc(&mut self) -> Result<(), Box<dyn std::error::Error>> {
    if self.client.close().is_err() {
        self.client.connect()?;
        self.client.close()?;
    }
    Ok(())
}
```

**Comment by vionya** [comment]
when you say "same effect as before", what is that effect? the most recent commit does indeed properly take ownership of then drop the file handle, closing the file.

**Comment by UnknownSuperficialNight** [comment]
> when you say "same effect as before", what is that effect? the most recent commit does indeed properly take ownership of then drop the file handle, closing the file.

The effect being that the RPC stays connected and nothing changes RPC still ticks away on discord and the activity never ends or clears, indicating that It's still connected as far as I'm aware.

I can test again if you like (Possibly record it), I don't have a Windows pc on me right now, so ill have to RDP into a friend's PC for testing.

On the contrary, RDP instantly stops on Linux when `.close()` is called, irregardless of the RDP activity state.

**Comment by vionya** [comment]
i believe this may be out of the control of the library then, because the file handle is being closed properly on both platforms. if the desired behavior is to ensure the activity goes away, make sure to call `.clear_activity()`

**Comment by ckcr4lyf** [comment]
FWIW: I just tried on Linux w/ `client.close()` , but the Activity is _not_ cleared. (Also tried on Windows 10; also does not get cleared).

Explicitly calling `.clear_activity()` works.

One thing to note: `.clear_activity()` has to be called from the same PID that set it, otherwise you'll be unable to clear the activity (unless you somehow save the PID of the process that set the activity), because it needs to be passed in the RPC call:

https://github.com/vionya/discord-rich-presence/blob/cf51648ef0745da8c56d5da9a5e9d64135a1735c/src/discord_ipc.rs#L189-L193
